### ISSUE TITLE
Unkown firmware on dump creation

### ISSUE THREAD

**Issue by Ka8oum** [mcDomDom/RTDProgrammer#1]
Hi,

I tried to add a comment under your post but I have a weird message (google translate) "If the body contains only alphanumeric characters, it cannot be written." and so it doesn't allow me to post there so I thought of asking here.

-----------------------------------

I believe I have setup similar to Newman (from the comments on your blog).
I followed your instructions and seemed to have been able to successfully read the firmware, I have a 512Kb File

it appears my screen is on /dev/i2c-21
I needed to run ./rtd2660 -r firmware.bin 21

I have the following output after the firmware reading:

Ready
Working with device 4a
JEDEC ID: 0x856013
Manufacturer Puya
Chip: P25Q40SH
Size: 512KB
Flash status register(S7-S0): 0xbc
Flash status register(S15-S8): 0x40
SaveFlash firmware.bin size=512(kbyte)
Reading addr 7fc00
done.
Received data CRC f4
Chip CRC f4
Success!

My board is a green pcb, here is the link to the exact one I bought
https://www.aliexpress.com/item/1005006266026368.html?spm=a2g0o.order_list.order_list_main.29.52511802eQuuMa

I have therefore an ipad screen attached on it.

I want to try your firmware modification because after changing the image orientation in the OSD I do not have any display output anymore and I hope I can change some settings there to put the controller back to factory defaults

when I try to do the dump of firmware.bin, I have "Unkown Firmware" message

Do you know how I can solve this?

**Comment by mcDomDom** [comment]
Hello. First, please send me the dumped firmware somehow. You may attach it as a reply to this comment.

**Comment by Ka8oum** [comment]
Hi,
Sorry for the delay I was not near my raspberry for the last couple of days.
Here is the firmware I could extract
[firmware.zip](https://github.com/mcDomDom/RTDProgrammer/files/14536501/firmware.zip)

**Comment by mcDomDom** [comment]
Hello. I filled in the area that seems to be the firmware settings storage area with 0xFF. Try writing with ./rtd2660 -w firmware_0x7B000_FF.bin 21
[firmware_0x7B000_FF.zip](https://github.com/mcDomDom/RTDProgrammer/files/14536757/firmware_0x7B000_FF.zip)

**Comment by Ka8oum** [comment]
Thanks for you help, unfortunately it doesn’t seem to wok
Here is what I get:
`~/RTDProgrammer $ ./rtd2660 -w firmware_0x7B000_FF.bin 21
Ready
Working with device 4a
JEDEC ID: 0x856013
Manufacturer Puya
Chip: P25Q40SH
Size: 512KB
Flash status register(S7-S0): 0xbe
Flash status register(S15-S8): 0x40
Check original firmware firmware_0x7B000_FF.bin
unknown firmware
original firm firmware_0x7B000_FF.bin not exist or invalid(nRet=0) `

**Comment by mcDomDom** [comment]
sorry. I forgot that there is a firmware check function.
The github source has been updated, so after importing it and building it, rename firmware_0x7B000_FF.bin to firmware_0x7B000_FF_force.bin and try writing it.

**Comment by Ka8oum** [comment]
Thank you so much, you saved my day!
